/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Pizza;

/**
 *
 * @author lucas.lmfreitas1
 */
public class Sabor extends javax.swing.JFrame {

   private ArrayList<Pizza> selectedPizzas = new ArrayList<>();
   private double Precototal = 0.0;
   
   public Sabor() {
        initComponents();
        Adicionar();
    }
private void Adicionar() {
        BtnCalabresa.addActionListener(evt -> SalvarPizzas("Calabresa",19.00));
        BtnMussarela.addActionListener(evt -> SalvarPizzas("Mussarela",18.00));
        BtnFrangoCatu.addActionListener(evt -> SalvarPizzas("Frango e Catupiry",22.00));
        BtnChocolate.addActionListener(evt -> SalvarPizzas("Chocolate",20.50));

        BtnFinalizar.addActionListener(evt -> MostrarPizzas());
    }
    private void SalvarPizzas(String pizzaSabor, double preco) {
        selectedPizzas.add(new Pizza(pizzaSabor, preco));
           Precototal += preco;
        JOptionPane.showMessageDialog(this, "Pizza Escolhida: " + pizzaSabor);
    }
  private void MostrarPizzas() {
        // Process the selected pizzas in the ArrayList
        StringBuilder message = new StringBuilder("Pizzas Escolhidas:\n");
        for (Pizza pizza : selectedPizzas) {
            message.append(pizza.getSabor()).append(" - R$").append(pizza.getPreco()).append("\n");
        }
         message.append("Preço Total: R$").append(Precototal);
        JOptionPane.showMessageDialog(this, message.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnFinalizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BtnChocolate = new javax.swing.JButton();
        BtnFrangoCatu = new javax.swing.JButton();
        BtnMussarela = new javax.swing.JButton();
        BtnCalabresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setToolTipText("");
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Escolha o sabor de sua pizza");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 20, 250, 20);

        BtnFinalizar.setBackground(new java.awt.Color(255, 224, 180));
        BtnFinalizar.setText("Finalizar Pedido");
        jPanel1.add(BtnFinalizar);
        BtnFinalizar.setBounds(200, 310, 160, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pizzaRedonda.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 80, 70, 70);

        BtnChocolate.setText("Chocolate                                                 R$20,50");
        BtnChocolate.setName("BtnChocolate"); // NOI18N
        BtnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChocolateActionPerformed(evt);
            }
        });
        jPanel1.add(BtnChocolate);
        BtnChocolate.setBounds(250, 240, 300, 50);

        BtnFrangoCatu.setText("Frango e Catupiry                                     R$22,00");
        BtnFrangoCatu.setName("BtnFrangoCatu"); // NOI18N
        BtnFrangoCatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFrangoCatuActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFrangoCatu);
        BtnFrangoCatu.setBounds(250, 120, 300, 50);

        BtnMussarela.setText("Mussarela                                                  R$18,00");
        BtnMussarela.setName("BtnMussarela"); // NOI18N
        BtnMussarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMussarelaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMussarela);
        BtnMussarela.setBounds(250, 60, 300, 50);

        BtnCalabresa.setText("Calabresa                                                  R$19,00");
        BtnCalabresa.setName("BtnCalabresa"); // NOI18N
        BtnCalabresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalabresaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCalabresa);
        BtnCalabresa.setBounds(250, 180, 300, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChocolateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnChocolateActionPerformed

    private void BtnFrangoCatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFrangoCatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFrangoCatuActionPerformed

    private void BtnMussarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMussarelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMussarelaActionPerformed

    private void BtnCalabresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalabresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalabresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sabor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalabresa;
    private javax.swing.JButton BtnChocolate;
    private javax.swing.JButton BtnFinalizar;
    private javax.swing.JButton BtnFrangoCatu;
    private javax.swing.JButton BtnMussarela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
